port: 47209
theme: light
text_size: big
show_dates: false
show_gantt: false
show_calendar: false
show_weekends: false
auto_refresh: true
default_duration: 0
colors:
  default: '#8c8c8c'
  FIX: '#ff0000'
  FEAT: '#0080ff'
  REFACTOR: '#ffbf00'
  PERF: '#ff33ff'
  TESTS: '#269900'
  DOCS: '#663300'
  ENV: '#999900'
  MISC: '#339999'
  DEADLINE: '#ffff00'
